name: share_plus_example
description: Demonstrates how to use the share_plus plugin.

dependencies:
  flutter:
    sdk: flutter
  share_plus:
    path: ../
  image_picker: ^0.8.4
  file_selector: ^0.9.2+1

dependency_overrides:
  share_plus_linux:
    path: ../../share_plus_linux
  share_plus_macos:
    path: ../../share_plus_macos
  share_plus_platform_interface:
    path: ../../share_plus_platform_interface
  share_plus_web:
    path: ../../share_plus_web
  share_plus_windows:
    path: ../../share_plus_windows

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"
